### ISSUE TITLE
"Package.swift has no Package.swift manifest for version 0.6.2 in .../Retry.git"

### ISSUE THREAD

**Issue by brunomunizaf** [icanzilb/Retry#8]
Hi,

Is this project still maintained? I'm having some trouble on using it with SPM.

**Comment by icanzilb** [comment]
@brunomunizaf I had few minutes and jumped in and fixed the package file and added correct tag https://github.com/icanzilb/Retry/releases/tag/0.6.3 👍🏼

**Comment by brunomunizaf** [comment]
Thanks a lot Marin, keep up the great work. You're amazing 🚀
